flexiform_wizard.flexiform_wizard.*:
  type: config_entity
  label: 'Wizard'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    use_admin_theme:
      type: boolean
      label: 'Whether or not to render this wizard in the admin theme'
    path:
      type: string
      label: 'Wizard path'
    access_logic:
      type: string
      label: 'Access logic'
    access_conditions:
      type: sequence
      label: 'Access Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Access Condition'
    parameters:
      type: sequence
      label: Parameter context list
      sequence:
        type: mapping
        label: Parameter context
        mapping:
          machine_name:
            type: string
            label: 'Machine-readable name'
          label:
            type: label
            label: 'Label of the provided entity'
          type:
            type: string
            label: 'Entity type'
    pages:
      type: sequence
      label: Operations list
      sequence:
        type: mapping
        label: Operation
        mapping:
          plugin:
            type: string
            label: 'Plugin ID'
          machine_name:
            type: string
            label: 'Machine-readable step name'
          label:
            type: label
            label: 'Step label'
          weight:
            type: integer
            label: 'Weight'
          settings:
            type: mapping
            label: 'Settings'
            mapping:
              context_mapping:
                type: sequence
                label: 'Context assignments'
                sequence:
                  type: string
